name: 'Create Release'

on:
  push:
    tags:
    - '*' # Mandatory as it's a release.

permissions:
  contents: write

jobs:
  qa:
    name: Build and deploy in QA
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: Eshop
    environment: qa

    steps:

    - uses: actions/checkout@v4

    - uses: ./.github/workflows/templates/build-dotnet
      with:
        project-path: ./Eshop/Eshop.csproj

    - uses: ./.github/workflows/templates/package-dotnet
      with:
        working-directory: ./Eshop

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: outputs
  


    