name: 'Code Freeze: Build and deploy in QA on push on release'

on:
  push:
    branches: [ main ]

jobs:
  qa:
    name: Build and deploy in QA
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: Eshop
    environment: qa

    steps:

    - uses: actions/checkout@v4

    - uses: ./.github/workflows/templates/build-dotnet
      with:
        project-path: ./Eshop/Eshop.csproj

    - uses: ./.github/workflows/templates/package-dotnet
      with:
        working-directory: ./Eshop

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: outputs
  


    