name: Dev CI/CD

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: Eshop
    environment: dev

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/workflows/templates/build-dotnet
      with:
        project-path: ./Eshop.csproj
    # - name: Create Infrastructure
    #   run: echo Run ARM templates commands...

    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v4
    #   with:
    #     dotnet-version: 8.0.x

    # - name: Restore dependencies
    #   run: dotnet restore

    # - name: Build
    #   run: dotnet build ./Eshop.csproj --no-restore

    - name: Publish code on Azure
      run: echo Run ARM templates commands...

    