name: Dev CI/CD

on:
  push:
    branches: [ develop ]

jobs:
  build:
    name: Build and deploy in Dev
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: Eshop
    environment: dev

    steps:
    - uses: actions/checkout@v4
    
    - uses: ./.github/workflows/templates/build-dotnet
      with:
        project-path: ./Eshop/Eshop.csproj
      
    - uses: ./.github/workflows/templates/package-dotnet
      with:
        working-directory: ./Eshop
        
    - name: Create Infrastructure
      run: echo Run ARM templates commands...

    - name: Publish code on Azure
      run: echo Run ARM templates commands...

    