name: 'Feature Freeze: Build and deploy in QA every night'

on:
  # This event will only trigger a workflow run if the workflow file is on the default branch.
  # See: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
  schedule:
    - cron: '0 0 * * *'

jobs:
  qa:
    if: ${{ vars.FREEZE_MODE == 'FEATURE' }}
    name: Build and deploy in QA every night
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: Eshop
    environment: qa

    steps:

    - uses: actions/checkout@v4
      with:
        ref: develop

    - uses: ./.github/workflows/templates/build-dotnet
      with:
        project-path: ./Eshop/Eshop.csproj

    - uses: ./.github/workflows/templates/package-dotnet
      with:
        working-directory: ./Eshop

    - name: Create Infrastructure
      run: echo Run ARM templates commands...
  
    - name: Publish code on Azure
      run: echo Run ARM templates commands...

    