name: 'Feature Freeze: Build and deploy in QA every night'

on:
  # This event will only trigger a workflow run if the workflow file is on the default branch.
  # See: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
  schedule:
    - cron: '*/5 * * * *'

jobs:
  qa:
    if: ${{ vars.FREEZE_MODE == 'FEATURE' }}
    name: Build and deploy in QA every night
    runs-on: ubuntu-latest
    environment: qa

    steps:

    # This is a community action as GitHub Actions can't do this by default using actions/download-artifact: 
    #  https://github.com/marketplace/actions/download-workflow-artifact
    - name: Download workflow artifact
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: dev-cicd.yml
        workflow_search: false
        workflow_conclusion: success
        branch: develop
        name: 'artifact'
        if_no_artifact_found: fail
  
    - name: Create Infrastructure
      run: |
        echo artifacts to be pushed:
        ls
        echo Run ARM templates commands...
  
    - name: Publish code on Azure
      run: echo Run ARM templates commands...

    