name: Feature Freeze

on:
  # This event will only trigger a workflow run if the workflow file is on the default branch.
  # See: https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule
  schedule:
    # - cron: '0 0 * * *'
    - cron: '*/5 * * * *'

jobs:
  qa:
    if: ${{ vars.FREEZE_MODE == 'FEATURE' }}
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: Eshop
    environment: qa

    steps:

    - uses: actions/checkout@v4
      with:
        ref: develop

    - name: Create Infrastructure
      run: echo Run ARM templates commands...

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build ./Eshop.csproj --no-restore

    - name: Publish code on Azure
      run: echo Run ARM templates commands...

    