name: 'QA to Prod on validation'

on:
  push:
    # Better option will be to have something like tags/0.0.1 or some conventions
    tags:        
      - '**' 

jobs:
  scan-repository:
    runs-on: ubuntu-latest
    outputs:
      current-branch: ${{ steps.get-branch-name.outputs.current-branch }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          ref: release

      - name: Get commit hash for the tag
        id: get-branch-name
        run: | 
          # Get commit hash for the tag
          commit_hash=$(git rev-parse ${{ github.ref }})
          echo $commit_hash
          # Determine branch containing the commit
          branch=$(git branch --contains="$commit_hash" | head -n1 | cut -c3-)
          echo $branch
          echo "current-branch=$branch" >> "$GITHUB_OUTPUT"

      - name: Show branch name
        run: echo "The tag was pushed to branch ${{ steps.get-branch-name.outputs.current-branch }}"

  qa:
    if: ${{ needs.scan-repository.outputs.current-branch == 'release' }}
    needs: scan-repository
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: Eshop
    environment: qa

    steps:

    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Create Infrastructure
      run: echo Run ARM templates commands...

    - uses: ./.github/workflows/templates/build-dotnet
      with:
        project-path: ./Eshop/Eshop.csproj

    - uses: ./.github/workflows/templates/package-dotnet
      with:
        working-directory: ./Eshop
 
  prod:
    runs-on: ubuntu-latest
    needs: qa
    environment: prod
    steps:

      - name: Download package code from QA
        uses: actions/download-artifact@v4
        with:
          name: 'artifact'

      - name: Create Infrastructure
        run: echo Run ARM templates commands...

      - name: Publish code on Azure
        run: echo Run ARM templates commands...
